name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm i -g npm@latest
      - run: npm ci --workspaces=false || npm install
      - run: npm install --workspaces
      - run: npm run build
      - run: npm run typecheck

